{
  "test_sequences" : {
    "failing.Failing2" : {
      "sequences" : [ "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = (byte) -1;\r\n    failing2_0.myIntInput = 0;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '#';\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    int int3 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    failing2_0.myIntInput = (short) 0;\r\n    failing2_0.myIntInput = 'a';\r\n    java.lang.Class<?> wildcardClass11 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    java.lang.Class<?> wildcardClass1 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    java.lang.Class<?> wildcardClass3 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = (short) -1;\r\n    java.lang.Class<?> wildcardClass7 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((-1));\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    int int3 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    failing2_0.myIntInput = 0;\r\n    failing2_0.myIntInput = (short) 100;\r\n    java.lang.Class<?> wildcardClass8 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    failing2_0.myIntInput = 0;\r\n    java.lang.Class<?> wildcardClass6 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    int int5 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    int int5 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    int int2 = failing2_0.myIntInput;\r\n    java.lang.Class<?> wildcardClass3 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = ' ';\r\n    failing2_0.myIntInput = (byte) 0;\r\n    int int9 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    int int2 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (short) 1;\r\n    java.lang.Class<?> wildcardClass5 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    java.lang.Class<?> wildcardClass4 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    int int5 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 35;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    int int10 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '#';\r\n    int int10 = failing2_0.myIntInput;\r\n    java.lang.Class<?> wildcardClass11 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = ' ';\r\n    failing2_0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) 'a');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    int int5 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(52);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    int int10 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    java.lang.Class<?> wildcardClass5 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    int int2 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) -1;\r\n    failing2_0.myIntInput = 97;\r\n    failing2_0.myIntInput = (byte) 100;\r\n    java.lang.Class<?> wildcardClass9 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = ' ';\r\n    failing2_0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) 10;\r\n    failing2_0.myIntInput = (byte) 10;\r\n    failing2_0.myIntInput = (byte) 10;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (short) 1;\r\n    java.lang.Class<?> wildcardClass6 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    int int2 = failing2_0.myIntInput;\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 0;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) 0;\r\n    java.lang.Class<?> wildcardClass10 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(97);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    java.lang.Object obj0 = new java.lang.Object();\r\n    java.lang.Class<?> wildcardClass1 = obj0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = ' ';\r\n    failing2_0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(52);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    failing2_0.myIntInput = 0;\r\n    failing2_0.myIntInput = 'a';\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 10;\r\n    failing2_0.myIntInput = (short) -1;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = (short) -1;\r\n    failing2_0.myIntInput = (-1);\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (short) -1;\r\n    java.lang.Class<?> wildcardClass7 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = 1;\r\n    int int3 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = ' ';\r\n    java.lang.Class<?> wildcardClass7 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) '#');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    java.lang.Class<?> wildcardClass7 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    int int10 = failing2_0.myIntInput;\r\n    java.lang.Class<?> wildcardClass11 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    int int7 = failing2_0.myIntInput;\r\n    int int8 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    int int5 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (short) -1;\r\n    failing2_0.myIntInput = (-1);\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = (byte) 1;\r\n    int int7 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    int int3 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    failing2_0.myIntInput = 0;\r\n    failing2_0.myIntInput = (short) 100;\r\n    failing2_0.myIntInput = ' ';\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) 0;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    failing2_0.myIntInput = 0;\r\n    failing2_0.myIntInput = 97;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    int int7 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((-1));\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    int int7 = failing2_0.myIntInput;\r\n    java.lang.Class<?> wildcardClass8 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    java.lang.Class<?> wildcardClass7 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    failing2_0.myIntInput = (short) 0;\r\n    failing2_0.myIntInput = '#';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (short) -1;\r\n    int int7 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 0;\r\n    failing2_0.myIntInput = (short) 100;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    int int7 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(97);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (-1);\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int7 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    int int2 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) -1;\r\n    failing2_0.myIntInput = (short) 0;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) 0;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    int int7 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) '4');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    int int5 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (short) 1;\r\n    failing2_0.myIntInput = 100;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    java.lang.Class<?> wildcardClass7 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) 0;\r\n    int int10 = failing2_0.myIntInput;\r\n    int int11 = failing2_0.myIntInput;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    int int7 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) '4');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    failing2_0.myIntInput = 0;\r\n    failing2_0.myIntInput = 0;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = ' ';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    int int7 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    failing2_0.myIntInput = (short) 100;\r\n    int int12 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = (byte) 10;\r\n    failing2_0.myIntInput = (byte) 10;\r\n    java.lang.Class<?> wildcardClass8 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    java.lang.Class<?> wildcardClass7 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    java.lang.Class<?> wildcardClass5 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    java.lang.Class<?> wildcardClass5 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 97;\r\n    failing2_0.myIntInput = (short) 10;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    failing2_0.myIntInput = (short) 0;\r\n    java.lang.Class<?> wildcardClass9 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 1;\r\n    int int5 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(97);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 0;\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    failing2_0.myIntInput = 10;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = ' ';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (short) 1;\r\n    java.lang.Class<?> wildcardClass3 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    failing2_0.myIntInput = (short) 0;\r\n    failing2_0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 'a';\r\n    failing2_0.myIntInput = 'a';\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    int int4 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = '4';\r\n    failing2_0.myIntInput = (short) 0;\r\n    failing2_0.myIntInput = ' ';\r\n    java.lang.Class<?> wildcardClass11 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    java.lang.Class<?> wildcardClass2 = failing2_0.getClass();\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    failing2_0.myIntInput = (-1);\r\n    int int3 = failing2_0.myIntInput;\r\n    failing2_0.myIntInput = 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException((int) (byte) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing2 failing2_0 = new failing.Failing2();\r\n    int int1 = failing2_0.myIntInput;\r\n    int int2 = failing2_0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing2_0.throwCaughtException(52);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n" ],
      "imports" : [ "org.junit.runners.MethodSorters", "static org.junit.Assert.assertNull", "org.junit.Test", "static org.junit.Assert.assertEquals", "org.junit.FixMethodOrder" ],
      "before_after_code_segments" : [ ]
    },
    "failing.Failing" : {
      "sequences" : [ "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int6 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (byte) -1;\r\n    java.lang.Class<?> wildcardClass10 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '4');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    int int10 = failing0.myIntInput;\r\n    int int11 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(97);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    int int10 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 10;\r\n    failing0.myIntInput = (byte) 1;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    failing0.myIntInput = ' ';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    int int10 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass11 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    failing0.myIntInput = '4';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (byte) -1;\r\n    int int10 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass11 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 1;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = (-1);\r\n    java.lang.Class<?> wildcardClass9 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) ' ');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 10;\r\n    int int5 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass6 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '#');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) 'a');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    int int6 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (byte) 0;\r\n    int int5 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    int int10 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(32);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    int int7 = failing0.myIntInput;\r\n    int int8 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass9 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int8 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass6 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass3 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    java.lang.Class<?> wildcardClass8 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = '4';\r\n    int int7 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = ' ';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '#');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    java.lang.Class<?> wildcardClass1 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 10;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 10;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 10;\r\n    failing0.myIntInput = (byte) -1;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 10;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    int int10 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    int int13 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    java.lang.Class<?> wildcardClass8 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int6 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((-1));\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    java.lang.Class<?> wildcardClass9 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 32;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int9 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass10 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (byte) 0;\r\n    failing0.myIntInput = ' ';\r\n    int int7 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) 'a');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int8 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = (byte) 100;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = '4';\r\n    failing0.myIntInput = 10;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass5 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    failing0.myIntInput = (short) 10;\r\n    int int7 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    failing0.myIntInput = 0;\r\n    java.lang.Class<?> wildcardClass12 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    int int7 = failing0.myIntInput;\r\n    failing0.myIntInput = 32;\r\n    failing0.myIntInput = (short) 1;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = (byte) 100;\r\n    java.lang.Class<?> wildcardClass9 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 0;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 10;\r\n    java.lang.Class<?> wildcardClass5 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    int int7 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass2 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    java.lang.Class<?> wildcardClass5 = failing0.getClass();\r\n}\r\n", "{    java.lang.Object obj0 = new java.lang.Object();\r\n    java.lang.Class<?> wildcardClass1 = obj0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    int int7 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = ' ';\r\n    int int9 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass10 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    failing0.myIntInput = (-1);\r\n    int int11 = failing0.myIntInput;\r\n    int int12 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass5 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    int int7 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass8 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int8 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = 32;\r\n    int int13 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    failing0.myIntInput = (-1);\r\n    failing0.myIntInput = 32;\r\n    int int13 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 100;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '4');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass6 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int8 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass9 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = (byte) 100;\r\n    failing0.myIntInput = ' ';\r\n    java.lang.Class<?> wildcardClass11 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 0;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 10;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 0;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    java.lang.Class<?> wildcardClass6 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    int int7 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int10 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    int int5 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    failing0.myIntInput = (short) 10;\r\n    int int7 = failing0.myIntInput;\r\n    int int8 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(97);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    failing0.myIntInput = (short) 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((-1));\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    failing0.myIntInput = 'a';\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (byte) 0;\r\n    failing0.myIntInput = ' ';\r\n    failing0.myIntInput = '4';\r\n    java.lang.Class<?> wildcardClass9 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 1;\r\n    java.lang.Class<?> wildcardClass6 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(97);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    failing0.myIntInput = (-1);\r\n    java.lang.Class<?> wildcardClass11 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    java.lang.Class<?> wildcardClass5 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 0;\r\n    int int7 = failing0.myIntInput;\r\n    int int8 = failing0.myIntInput;\r\n    int int9 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 0;\r\n    int int7 = failing0.myIntInput;\r\n    int int8 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass9 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (short) 0;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 10;\r\n    int int9 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 10;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (short) 10;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = ' ';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    int int10 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    java.lang.Class<?> wildcardClass13 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 10;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 10;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '4');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    failing0.myIntInput = (short) 1;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '#');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((-1));\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    int int6 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    int int10 = failing0.myIntInput;\r\n    failing0.myIntInput = 10;\r\n    int int13 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass4 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass5 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 10;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int5 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '4');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    java.lang.Class<?> wildcardClass3 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) ' ');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(97);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    failing0.myIntInput = (short) 10;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (byte) 0;\r\n    failing0.myIntInput = ' ';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '#');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = ' ';\r\n    java.lang.Class<?> wildcardClass9 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((-1));\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    int int6 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '4');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int9 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (byte) 100;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = (byte) 100;\r\n    failing0.myIntInput = ' ';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    failing0.myIntInput = (-1);\r\n    int int11 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = '4';\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 1;\r\n    int int6 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = '4';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (byte) 0;\r\n    failing0.myIntInput = ' ';\r\n    failing0.myIntInput = 32;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = (byte) 100;\r\n    int int9 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '#');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    failing0.myIntInput = (-1);\r\n    failing0.myIntInput = 32;\r\n    int int13 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (short) 1;\r\n    failing0.myIntInput = (short) 1;\r\n    failing0.myIntInput = '#';\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    int int10 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass11 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 1;\r\n    failing0.myIntInput = (short) 1;\r\n    int int8 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = (byte) 10;\r\n    failing0.myIntInput = (byte) 1;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    int int7 = failing0.myIntInput;\r\n    failing0.myIntInput = 32;\r\n    int int10 = failing0.myIntInput;\r\n    int int11 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 97;\r\n    failing0.myIntInput = (byte) 100;\r\n    failing0.myIntInput = (byte) 1;\r\n    java.lang.Class<?> wildcardClass8 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) ' ');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 10;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 10;\r\n    int int7 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 1;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = '#';\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass4 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 0;\r\n    int int7 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass8 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (byte) 0;\r\n    failing0.myIntInput = ' ';\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 100;\r\n    failing0.myIntInput = (short) 10;\r\n    int int7 = failing0.myIntInput;\r\n    failing0.myIntInput = '#';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) 0);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 100);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (short) 10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 0;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    int int7 = failing0.myIntInput;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = (byte) 1;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    failing0.myIntInput = 10;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) (byte) -1);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    int int7 = failing0.myIntInput;\r\n    failing0.myIntInput = 32;\r\n    int int10 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    int int6 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int9 = failing0.myIntInput;\r\n    java.lang.Class<?> wildcardClass10 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = 97;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 10;\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    int int1 = failing0.myIntInput;\r\n    int int2 = failing0.myIntInput;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    failing0.myIntInput = '4';\r\n    java.lang.Class<?> wildcardClass7 = failing0.getClass();\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    int int4 = failing0.myIntInput;\r\n    int int5 = failing0.myIntInput;\r\n    failing0.myIntInput = 'a';\r\n    int int8 = failing0.myIntInput;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException(10);\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    int int3 = failing0.myIntInput;\r\n    failing0.myIntInput = 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    failing0.myIntInput = (byte) 0;\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) '#');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n", "{    failing.Failing failing0 = new failing.Failing();\r\n    failing0.myIntInput = (byte) -1;\r\n    failing0.myIntInput = (short) 0;\r\n    failing0.myIntInput = (short) 10;\r\n    failing0.myIntInput = ' ';\r\n    // The following exception was thrown during execution in test generation\r\n    try {\r\n        failing0.throwCaughtException((int) 'a');\r\n        org.junit.Assert.fail(\"Expected exception of type java.io.IOException; message: Throwing IOException\");\r\n    } catch (java.io.IOException e) {\r\n    // Expected exception.\r\n    }\r\n}\r\n" ],
      "imports" : [ "org.junit.runners.MethodSorters", "static org.junit.Assert.assertNull", "org.junit.Test", "static org.junit.Assert.assertEquals", "org.junit.FixMethodOrder" ],
      "before_after_code_segments" : [ ]
    }
  },
  "test_generation_tool" : "RandoopTestGenerator"
}